# Generated by Django 3.2.2 on 2023-03-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('points_required', models.IntegerField()),
                ('coupen_code', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='reward_product')),
                ('expiray_date', models.DateField()),
                ('starting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('regular_price', models.IntegerField()),
                ('off_percentage', models.IntegerField(max_length=100)),
                ('duration', models.ImageField(default=0, upload_to='')),
                ('reward_point', models.IntegerField()),
            ],
        ),
    ]
