# Generated by Django 3.2.2 on 2023-03-03 08:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20230303_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_small',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 13, 58, 20, 805782)),
        ),
        migrations.AlterField(
            model_name='service_small',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 13, 58, 20, 805782)),
        ),
        migrations.AlterField(
            model_name='service_small',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
