# Generated by Django 3.2.2 on 2023-03-04 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230303_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_small',
            name='service_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='service_small',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 4, 6, 35, 1, 622439)),
        ),
        migrations.AlterField(
            model_name='service_small',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 4, 6, 35, 1, 622439)),
        ),
    ]
